name: Keep Replit Alive

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Replit
        run: curl -I https://65c34bd3-0a35-45e4-9fc9-578496f6b07b-00-7pm0fggyyzie.spock.replit.dev
